#!/usr/bin/bash

if [ $# -eq 0 ]; then
    echo "Error: There is no project name"
    exit 1
fi

project_name=$1

your_name="Aki"
your_title="MyTitle"

mkdir ${project_name}
touch ${project_name}/main.tex
mkdir ${project_name}/src
touch ${project_name}/src/a.tex
touch ${project_name}/Makefile

dirname $0|xargs -I@ cat @/config/Makefile_template > ${project_name}/Makefile
dirname $0|xargs -I@ cat @/config/main_template.tex|sed s/TITLE/${your_title}/| sed s/NAME/${your_name}/> ${project_name}/main.tex
